import Foundation

// MARK: - The two languages
//
// Vocast has two language concepts and they are independent. Keeping them apart is
// the whole point of this layer, so they are separate types rather than two String
// properties that could be assigned to each other by accident.
//
//   InterfaceLanguage  the language of the UI chrome. Pure presentation, one per
//                      install, changeable at any time with no restart. Changing it
//                      must never touch a voice profile.
//   VoiceLanguage      the language a cloned voice speaks. It drives the guided
//                      script and the Whisper transcription that becomes the clone's
//                      reference text, so it affects quality, not just wording. Set
//                      once, before recording, and immutable afterwards.

/// The language of the app UI. Presentation only.
enum InterfaceLanguage: String, CaseIterable, Identifiable {
    case en, ko
    var id: String { rawValue }

    /// Always shown in its own language, the way a language picker should read.
    var nativeName: String { self == .ko ? "한국어" : "English" }

    /// What the Mac is set to, falling back to English.
    static var systemDefault: InterfaceLanguage {
        (Locale.preferredLanguages.first ?? "en").hasPrefix("ko") ? .ko : .en
    }
}

/// The language a voice speaks. Chosen before recording, then locked.
enum VoiceLanguage: String, CaseIterable, Identifiable {
    case en, ko
    var id: String { rawValue }

    var nativeName: String { self == .ko ? "한국어" : "English" }

    /// Quality gates, golden fixtures and the human baseline were measured on Korean
    /// only. Anything else scores against a baseline that does not apply, so the
    /// scorecard hides those numbers instead of implying they mean something.
    var hasQualityBaseline: Bool { self == .ko }

    /// Profiles created before voices carried a language are read as Korean, which
    /// is what the engine assumed at the time.
    init(profileCode: String?) { self = profileCode == "en" ? .en : .ko }
}

// MARK: - String table
//
// Every user-facing string resolves through here, keyed by the interface language.
// Taken verbatim from the design handoff's string table so the copy stays the
// reviewed copy. English is sentence case with no exclamation marks or emoji;
// Korean is 해요체, plain and unhyped, with product and technical names left in
// Latin (Vocast, MCP, API).

struct Strings {
    let lang: InterfaceLanguage
    private let t: [String: String]

    init(_ lang: InterfaceLanguage) {
        self.lang = lang
        self.t = lang == .ko ? Strings.ko : Strings.en
    }

    /// Look up a key. Falls back to English, then to the key itself, so a missing
    /// translation degrades to readable text rather than an empty label.
    subscript(_ key: String) -> String {
        t[key] ?? Strings.en[key] ?? key
    }

    /// Fill `{a}` and `{b}` placeholders, used by the mismatch and baseline copy.
    func f(_ key: String, a: String = "", b: String = "") -> String {
        self[key].replacingOccurrences(of: "{a}", with: a)
                 .replacingOccurrences(of: "{b}", with: b)
    }

    /// Fill named `{token}` placeholders from a dictionary. Order-independent, so a
    /// translation can move tokens around. Used by the second-tier strings whose
    /// placeholders go beyond the original `{a}`/`{b}` pair (`{n}`, `{mode}`,
    /// `{detail}`, `{reason}`, `{metric}`, `{stage}`, `{name}`, `{version}`,
    /// `{duration}`, `{file}`, `{profile}`, `{total}`).
    func f(_ key: String, _ tokens: [String: String]) -> String {
        var out = self[key]
        for (name, value) in tokens {
            out = out.replacingOccurrences(of: "{\(name)}", with: value)
        }
        return out
    }

    /// A language's name as it should appear inside a sentence in the current UI
    /// language, which is not the same as its native name.
    func nameOf(_ v: VoiceLanguage) -> String {
        v == .ko ? self["langOfKorean"] : self["langOfEnglish"]
    }

    static let en: [String: String] = [
        "korean": "Korean", "english": "English",
        "langOfEnglish": "English", "langOfKorean": "Korean",

        // Hover tooltips for icon-only buttons.
        "tipPlayBlock": "Play from this paragraph",
        "tipPlayPause": "Play / pause",
        "tipRegen": "Re-render this paragraph",
        "tipScorecard": "Show quality scorecard",
        "tipInspector": "Show or hide the side panel",

        "search": "Search", "library": "Library", "settings": "Settings",
        "offline1": "On this Mac, offline", "offline2": "Nothing leaves your device",
        "nStudio": "Studio", "nVoices": "Voices", "nDenoise": "Denoise", "nTasks": "Tasks",
        "subStudio": "Write, render, and narrate", "subVoices": "Clone and manage your voice",
        "subDenoise": "Clean up audio and video", "subTasks": "Running, queued, and done",
        "newNarration": "New narration", "newVoice": "New voice",
        "importAudio": "Import audio", "clearFinished": "Clear finished",

        "scriptPlaceholder": "Paste or write your script. Up to 20,000 characters.",
        "nothingYet": "Nothing yet.", "pasteSample": "Paste a sample script",
        "renderBlurb": "Render turns your script into editable paragraph blocks. Each block can be replayed, re-rendered, and scored on its own.",
        "renderNarration": "Render narration", "blocks": "Blocks", "karaoke": "Karaoke",
        "blocksTotal": "blocks", "totalSuffix": "total",
        "exportSel": "Export selection", "exportNarration": "Export narration",

        "yourVoices": "Your voices", "storedHere": "stored on this Mac",
        "newVoiceHint": "Record about 90 seconds of guided lines to clone your voice.",
        "createProfile": "Create a voice profile",
        "pickLangTitle": "What language will this voice speak?",
        "pickLangBody": "The guided lines and the transcription that trains the clone are written for this language. Choose before you record, it can't be changed afterwards.",
        "pickLangLocked": "Locked once recording starts. To use another language, create a new voice.",
        "startRecording": "Start recording", "changeLang": "Change",
        "readEachLine": "Read each line aloud in your normal speaking voice. About 90 seconds total.",
        "voiceLangLabel": "Voice language", "lineOf": "Line", "of": "of", "captured": "captured",
        "readThisLine": "Read this line", "focus": "Focus", "coach": "Coaching",
        "record": "Record", "stop": "Stop", "reRecord": "Re-record", "retake": "Retake",
        "nextLine": "Next line", "buildProfile": "Build profile",
        "grpKorean": "Korean voices", "grpEnglish": "English voices",
        "profiles": "profiles", "similarity": "Similarity",
        "baselineValidated": "baseline validated", "noBaselineYet": "no baseline yet",

        "mismatchTag": "Different language",
        "mismatchBanner": "This paragraph looks like {a}, but the voice speaks {b}. It will still render, quality may drop.",
        "mixedOk": "Mixed script is fine: {b} with the occasional {a} term reads normally.",
        "tryMismatch": "Try a script in another language",

        "noBaselineGate": "No quality baseline for {b} yet",
        "noBaselineBody": "Vocast has not validated a scoring baseline for {b}. Prosody scores are hidden rather than shown against a baseline that doesn't apply.",
        "measured": "measured", "hidden": "no baseline",
        "qualityScorecard": "Quality scorecard", "block": "block",
        "gatePass": "Passed quality gate",
        "qualityReport": "Quality report", "jobDetailT": "Job detail", "inspectorT": "Inspector",
        "hintStudio": "Render your script to see a quality scorecard for each block here.",
        "hintVoices": "Select a voice, or open a profile to see its versions and source clips.",
        "hintDenoise": "Import a file and run a cleanup to see the quality report here.",
        "hintGeneric": "Contextual detail appears here.",

        "setGeneral": "General", "setModels": "Models", "setAudio": "Audio",
        "setPrivacy": "Privacy", "setMcp": "MCP server", "setAbout": "About",
        "setLanguage": "Language", "setLangTitle": "Language",
        "setLangBlurb": "Set the interface language. Each voice keeps its own language, chosen when you create it.",
        "interfaceLanguage": "Interface language",
        "interfaceLangDetail": "The language of buttons, labels, and text in Vocast",
        "applyNow": "Applied immediately, no restart",
        "voiceLangSetting": "Voice languages",
        "voiceLangSettingDetail": "Set per voice when you create it, not here",
        "guaranteeNote": "Changing the interface language does not change any voice. Each voice keeps the language it was recorded in.",
        "obLangTitle": "Choose your language",
        "obLangBody": "This sets the language of the Vocast interface. You choose each voice's language later, when you create it.",
        "obLangHint": "Detected from macOS. You can change this anytime in Settings.",
        "continue": "Continue",

        // MARK: added from i18n-strings.md handoff
        "obWelcomeTitle": "Your voice, on your Mac",
        "obWelcomeBody": "Clone your voice, narrate any script, and clean up audio. No account, no server. It all runs on this Mac and works offline after a one-time model download.",
        "obPillLocal": "Runs on this Mac",
        "obPillNoUpload": "Nothing uploaded",
        "obPillOffline": "Works offline",
        "obGetStarted": "Get started",
        "obTierBalanced": "Balanced",
        "obTierBalancedBody": "Fast voice model plus transcription.",
        "obTierHighQ": "High quality",
        "obTierHighQBody": "Adds the larger, higher quality voice.",
        "obDownloadModels": "Download models",
        "obDownloadNote": "Downloaded once to this Mac and kept in the app's own folder. Nothing is uploaded.",
        "obPreparingEngine": "Preparing the engine on this Mac.",
        "obDownloading": "Downloading",
        "obModelsReady": "All models downloaded",
        "obMicTitle": "Microphone access",
        "obMicBody": "Vocast needs your microphone to record voice samples. Recordings stay on this device and are never uploaded.",
        "obMicAllow": "Allow microphone",
        "obMicNotNow": "Not now",
        "obReadyTitle": "You are set up",
        "obReadyBody": "Create a voice profile to start narrating, or explore the studio first.",
        "obReadyCreate": "Create first voice",
        "obReadyExplore": "Explore the studio",
        "dnDropTitle": "Drop an audio or video file to clean",
        "dnFormats": "WAV, MP3, M4A, MP4, MOV. Processed on this Mac.",
        "dnChooseFile": "Choose file",
        "dnRecentJobs": "Recent jobs",
        "dnModeStandard": "Standard",
        "dnModeStandardBody": "Fast filtering. Removes steady background noise and hum with light touch.",
        "dnModeResynth": "Resynth",
        "dnModeResynthBody": "Full resynthesis. Higher effort, rebuilds the voice for the cleanest result.",
        "dnNotInstalled": "not installed",
        "dnStartCleanup": "Start cleanup",
        "dnCleaning": "Cleaning audio",
        "dnExport": "Export cleaned file",
        "dnOriginal": "Original",
        "dnCleaned": "Cleaned",
        "dnCleanedStatus": "cleaned · {mode}",
        "dnNow": "Now: {side}",
        "dnSpeechPreservedTail": "speech preserved",
        "taskGroupRunning": "Running",
        "taskGroupQueued": "Queued",
        "taskGroupDone": "Done",
        "taskWaiting": "Waiting",
        "taskFailed": "Failed",
        "taskOpen": "Open",
        "taskCancel": "Cancel",
        "taskDismiss": "Dismiss",
        "vBuildingTitle": "Building your voice profile",
        "vResultTitle": "Voice profile ready",
        "vResultBody": "Renders will follow the rhythm and tone the app measured from your voice. You can reinforce this profile later by adding more clips.",
        "vStartNarrating": "Start narrating",
        "vViewInLibrary": "View in library",
        "vDefaultPill": "Default",
        "vVersionHistory": "Version history",
        "vOneVersion": "This profile has one version.",
        "vCurrent": "current",
        "vRollBack": "Roll back",
        "vSourceClips": "Source clips",
        "vReinforce": "Reinforce",
        "vSetDefault": "Set as default",
        "vDeleteProfile": "Delete profile",
        "vNotFound": "Profile not found.",
        "vLevelLabel": "LVL",
        "setGeneralBlurb": "Appearance, startup, and default behavior.",
        "setAppearance": "Appearance",
        "setAppearanceSub": "Dark is the only theme for now.",
        "setLaunchLogin": "Launch at login",
        "setDefaultProfile": "Default voice profile",
        "setModelsBlurb": "Downloaded voice and transcription models, kept in the app's own folder. Nothing is uploaded.",
        "setDownloadHighQ": "Download high quality voice model (2.9 GB)",
        "setAudioBlurb": "Input device and export format.",
        "setInputDevice": "Input device",
        "setExportFormat": "Export format",
        "setSampleRate": "Sample rate",
        "setPrivacyBlurb": "All generation and cleanup happen on device. No account, no server, no telemetry.",
        "setPrivacyStatus": "Privacy and local status",
        "setMcpBlurb": "Let an AI agent (for example Claude) call Vocast actions on this Mac through a local MCP server. Off by default. Nothing is exposed to the network.",
        "setMcpEnable": "Enable local MCP server",
        "setMcpExposed": "Exposed actions",
        "setMcpEmpty": "The engine has not reported its tools yet.",
        "setAbtVersion": "Version",
        "setAbtLicense": "License",
        "setAbtRequirements": "Requirements",
        "setAbtLicenseValue": "One-time purchase, $49",
        "setAbtRequirementsValue": "macOS 14 or later, Apple Silicon",
        "scSubMetrics": "Sub-metrics",
        "scPNSName": "Prosody north-star",
        "scSpeechPreserved": "Speech preserved",
        "scPauseSupp": "Pause suppression",
        "scVoiceSim": "Voice similarity",
        "scSubEnding": "Ending style",
        "scSubStress": "Energy stress",
        "scSubDrop": "Ending drop",
        "scSubClarity": "Word clarity",
        "inspEtaNote": "ETA comes from how long jobs like this actually took on this Mac.",
        "scFootnotePNS": "PNS is the prosody north-star: rhythm, emphasis, and phrasing scored against your own voice. Sub-scores run 0 to 1, higher is better. Blocks at 82 or above meet the quality bar. Measured on this Mac.",
        "scFootnoteDenoise": "Speech preserved is how much of your voice energy was kept. Pause suppression is how much noise was removed from the silences. Measured on this Mac.",
        "btnCancel": "Cancel",

        // MARK: Part 2 census + Part B + D1 (second-tier strings, wired 2026-07-23)
        "menuNewNarration": "New narration",
        "menuNewVoice": "New voice",
        "menuSettings": "Settings",
        "menuImportToClean": "Import audio to clean",
        "menuRender": "Render",
        "menuRenderNarration": "Render narration",
        "menuRegenerateBlock": "Regenerate block",
        "menuToggleInspector": "Toggle inspector",
        "menuSearch": "Search",
        "menuGroupVoice": "Voice",
        "menuPause": "Pause",
        "menuPlay": "Play",
        "stageRendering": "Rendering",
        "stageCleaning": "Cleaning",
        "stageBuilding": "Building",
        "stageRerendering": "Re-rendering",
        "stageRendered": "Rendered",
        "stPreparing": "Preparing",
        "stPreparingVoice": "Preparing the voice",
        "stGeneratingSpeech": "Generating speech",
        "stComposing": "Composing",
        "stGenerating": "Generating",
        "stAnalyzingVoice": "Analyzing your voice",
        "stMeasuringStyle": "Measuring your style",
        "stPreparingClips": "Preparing clips",
        "stAnalyzingClips": "Analyzing your clips",
        "stReadingFile": "Reading the file",
        "stBuildingPreview": "Building preview",
        "stMeasuringQuality": "Measuring quality",
        "stCleaningAudio": "Cleaning audio",
        "toNarrationReady": "Narration is ready.",
        "toBlockRerendered": "Block {n} re-rendered.",
        "toVoiceReady": "Voice profile ready.",
        "toProfileReinforced": "Profile reinforced.",
        "toCleanupDone": "Cleanup done, {mode} mode.",
        "toCleanedExported": "Cleaned file exported.",
        "toProfileDeleted": "Profile deleted.",
        "toSetDefault": "Set as default.",
        "toNarrationExported": "Narration exported to your Downloads folder.",
        "toBlocksExported": "Selected blocks exported to your Downloads folder.",
        "toCleanedExportedDl": "Cleaned file exported to your Downloads folder.",
        "toRolledBack": "Rolled back to v{n}.",
        "errEngineUnreachable": "Could not reach the local engine. Is it running?",
        "errEngineUnreachableShort": "Could not reach the local engine.",
        "errDownloadStart": "Could not start the model download. Is the engine running?",
        "errNoSingleBlock": "This narration cannot regenerate single blocks. Render it again first.",
        "errMicStart": "Could not start the microphone. Allow microphone access and try again.",
        "errNeedOneLine": "Record at least one line first.",
        "errRollback": "Could not roll back.",
        "errReinforce": "Reinforce failed.",
        "errReinforceProfile": "Could not reinforce the profile.",
        "errImportFirst": "Import a file first.",
        "errExportCleaned": "Could not export the cleaned file.",
        "errDownloadError": "Download error: {detail}",
        "errNarrationFailed": "Narration failed: {detail}",
        "errBlockRerenderFailed": "Block {n} could not be re-rendered: {detail}",
        "errBuildFailed": "Build failed: {detail}",
        "errCleanupFailed": "Cleanup failed: {detail}",
        "jobType": "Type",
        "jobTarget": "Target",
        "jobProfile": "Profile",
        "jobElapsed": "Elapsed",
        "inspNoScores": "The engine reported no quality scores for this block.",
        "inspSelectJob": "Select a running job to see its progress and details.",
        "jobKindNarration": "Narration render",
        "jobKindDenoise": "Denoise",
        "jobKindVoiceBuild": "Voice profile build",
        "inspMetaBlock": "block {n}",
        "inspMetaCleaned": "cleaned",
        "inspMetaRunning": "running",
        "scNeedsAttention": "Needs attention: {reason}",
        "scReasonBelowBar": "prosody below the 82 quality bar",
        "scReasonSubWeak": "{metric} below target",
        "scReasonSimLow": "voice similarity below target",
        "scReasonSpeechLoss": "speech loss above target",
        "dnSubSim": "How closely the cleaned voice matches the original.",
        "dnSubSpeech": "How much of your voice energy was kept.",
        "dnSubPause": "Noise removed from the silences.",
        "dnProcessingSubhead": "{mode} mode, on this Mac.",
        "obDownloadHeading": "Download the voice models",
        "obDownloadHeadingDone": "Voice models ready",
        "mdlVoiceFast": "Voice model (fast)",
        "mdlVoiceHighQ": "Voice model (high quality)",
        "mdlTranscription": "Transcription model",
        "mdlVoiceGeneric": "Voice models",
        "obGbOnMac": "{n} GB on this Mac",
        "mdlNoiseRemoval": "Noise removal",
        "setInstalled": "installed",
        "setDownloadingGB": "Downloading, {a} / {b} GB",
        "setBundled": "bundled",
        "privSubLocal": "Generation uses this machine only.",
        "privSubNoUpload": "Your audio never leaves the device.",
        "privSubOffline": "After the first-run model download.",
        "privWhereStored": "Where data is stored",
        "mcpRunning": "Running · localhost only",
        "mcpDisabled": "Disabled",
        "mcpActionEnabled": "enabled",
        "mcpActionDisabled": "disabled",
        "vRecStatusRecording": "Recording",
        "vRecStatusCaptured": "Captured",
        "vRecStatusReady": "Ready to record",
        "vGuideWaiting": "Waiting for the engine's guided script.",
        "vBuildSubline": "{stage} on this Mac. This runs as a background job, you can keep working.",
        "vResultSubline": "{name} is now in your library and set as default.",
        "vStatClips": "clips analyzed",
        "vStatDuration": "of your voice",
        "vStatVersion": "version",
        "vDefaultName": "Your voice",
        "vBuildNow": "Build now ({n})",
        "vCurrentVersion": "Current version",
        "vEarlierVersion": "Earlier version",
        "vCardClips": "{version} · {n} clips",
        "vMetaSourceClips": "{version} · {n} source clips · {duration}",
        "vSourceBlurb": "{n} clips, {duration} total. Drag audio files here to reinforce this profile with more of your voice.",
        "stuScorecardNote": "Measured on this Mac from your own renders.",
        "etaFinishing": "finishing",
        "vpA11yProfile": "Voice profile",
        "vpA11yProfileHint": "Opens the list of voice profiles",
        "vpA11yProfiles": "Voice profiles",
        "vpEmptyNoProfiles": "No voice profiles yet",
        "jobTitleNarration": "Narration render",
        "jobTitleNarrationBlock": "Narration render, block {n}",
        "jobTitleVoiceBuild": "Voice profile build",
        "jobTitleDenoise": "Denoise, {file}",
        "jobSubTts": "{profile} · TTS on this Mac",
        "jobSubClipsAnalyzing": "{n} clips · analyzing",
        "jobSubClips": "{n} clips",
        "jobSubMode": "{mode} mode",
        "jobTargetBlockOf": "block {n} of {total}",
        "jobTargetClips": "{n} clips",
        "jobTimeJustNow": "just now",
        "jobTimeFailed": "failed",
        "jobElapsedS": "{n}s elapsed",
        "jobSpeechPreservedPct": "{n}% speech preserved",

        // Authored in-house to close small gaps the designer handoff did not cover.
        // Low-visibility strings; flag for ratification in a later handoff pass.
        "stDone": "Done",
        "jobTargetNarration": "narration",
        "vNoProfileFacts": "no voice profile",
        "dnProcessingSubheadStage": "{stage}, on this Mac.",
        "errUnknownDetail": "unknown error",

        // Studio narration library.
        "libSearchPlaceholder": "Search narrations",
        "libSortNewest": "Newest first",
        "libBlocksN": "{n} blocks",
        "libVoiceNone": "No voice",
        "rowOpen": "Open", "rowRename": "Rename", "rowDuplicate": "Duplicate",
        "rowExport": "Export", "rowDelete": "Delete",
        "libEmptyTitle": "No narrations yet",
        "libEmptyBody": "Paste a script and render it with a voice, and it is saved here.",
        "libEmptyCta": "New narration",
        "editorVoiceGone": "This narration's voice was deleted. You can play and export it, but pick a voice again to re-render.",
        "backToLibrary": "Library",
        "untitledNarration": "Untitled narration",
        "exportTitle": "Export",
        "expAudioH": "Audio", "expSubH": "Subtitles", "expProjectH": "Project",
        "expScopeWhole": "Whole narration", "expScopeSelected": "Selected blocks",
        "expAudioHint": "Export the whole narration or selected blocks as an audio file.",
        "expSubHint": "Subtitles timed to the narration's blocks.",
        "expProjHint": "Back it up or move it to another Mac.",
        "expProjectExport": "Export .vocast file", "expProjectImport": "Import .vocast file",
        "exportedTitle": "Export finished",
        "exportedBody": "Saved {file} to your Downloads folder.",
        "renameTitle": "Rename narration",
        "renameHint": "The title is made automatically from the script's first line.",
        "renameSave": "Save",
        "delTitle": "Delete this narration?",
        "delBody": "Deleting removes the script and the generated audio. This cannot be undone.",
        "delConfirm": "Delete", "delCancel": "Cancel",
        "libSoon": "Coming soon.",
        "toNarrationDeleted": "Narration deleted.",
        "errOpenNarration": "Could not open this narration.",
        "errExport": "Export failed.",
        "relJustNow": "just now",
        "relMinAgo": "{n} min ago", "relHourAgo": "{n} hr ago",
        "relYesterday": "Yesterday", "relDayAgo": "{n} days ago", "relLastWeek": "Last week",
    ]

    static let ko: [String: String] = [
        "korean": "한국어", "english": "English",
        "langOfEnglish": "영어", "langOfKorean": "한국어",

        // 아이콘 버튼 호버 툴팁.
        "tipPlayBlock": "이 문단부터 재생",
        "tipPlayPause": "재생 / 일시정지",
        "tipRegen": "이 문단 다시 렌더",
        "tipScorecard": "품질 점수표 보기",
        "tipInspector": "사이드 패널 열기/닫기",

        "search": "검색", "library": "라이브러리", "settings": "설정",
        "offline1": "이 맥에서, 오프라인", "offline2": "기기 밖으로 나가지 않아요",
        "nStudio": "스튜디오", "nVoices": "보이스", "nDenoise": "잡음 제거", "nTasks": "작업",
        "subStudio": "쓰고, 생성하고, 낭독하기", "subVoices": "목소리를 복제하고 관리하기",
        "subDenoise": "오디오와 영상 잡음 정리", "subTasks": "진행·대기·완료",
        "newNarration": "새 나레이션", "newVoice": "새 목소리",
        "importAudio": "오디오 가져오기", "clearFinished": "완료 항목 정리",

        "scriptPlaceholder": "원고를 붙여넣거나 직접 쓰세요. 최대 20,000자.",
        "nothingYet": "아직 비어 있어요.", "pasteSample": "샘플 원고 붙여넣기",
        "renderBlurb": "생성하면 원고가 편집 가능한 문단 블록으로 나뉘어요. 블록마다 다시 재생·재생성하고 품질을 채점할 수 있어요.",
        "renderNarration": "낭독 생성", "blocks": "블록", "karaoke": "가라오케",
        "blocksTotal": "블록", "totalSuffix": "합계",
        "exportSel": "선택 내보내기", "exportNarration": "나레이션 내보내기",

        "yourVoices": "내 목소리", "storedHere": "개 · 이 맥에 저장됨",
        "newVoiceHint": "안내 문장을 약 90초 낭독하면 목소리가 복제돼요.",
        "createProfile": "목소리 프로필 만들기",
        "pickLangTitle": "이 목소리는 어떤 언어로 말하나요?",
        "pickLangBody": "안내 문장과, 클론을 학습시키는 전사(轉寫)가 이 언어 기준으로 작성돼요. 녹음 전에 고르세요. 시작한 뒤에는 바꿀 수 없어요.",
        "pickLangLocked": "녹음을 시작하면 잠겨요. 다른 언어를 쓰려면 새 목소리를 만드세요.",
        "startRecording": "녹음 시작", "changeLang": "변경",
        "readEachLine": "평소 말하는 목소리로 각 문장을 소리 내어 읽어 주세요. 전체 약 90초예요.",
        "voiceLangLabel": "목소리 언어", "lineOf": "문장", "of": "/", "captured": "녹음됨",
        "readThisLine": "이 문장을 읽어 주세요", "focus": "초점", "coach": "코칭",
        "record": "녹음", "stop": "정지", "reRecord": "다시 녹음", "retake": "다시 하기",
        "nextLine": "다음 문장", "buildProfile": "프로필 빌드",
        "grpKorean": "한국어 목소리", "grpEnglish": "영어 목소리",
        "profiles": "개 프로필", "similarity": "유사도",
        "baselineValidated": "기준선 검증됨", "noBaselineYet": "기준선 없음",

        "mismatchTag": "다른 언어",
        "mismatchBanner": "이 문단은 {a}처럼 보이는데, 이 목소리는 {b}를 말해요. 생성은 되지만 품질이 떨어질 수 있어요.",
        "mixedOk": "섞인 표기는 괜찮아요. {b}에 {a} 용어가 가끔 섞이는 건 자연스럽게 읽혀요.",
        "tryMismatch": "다른 언어 원고로 시도해 보기",

        "noBaselineGate": "아직 {b} 품질 기준선이 없어요",
        "noBaselineBody": "Vocast가 {b}의 채점 기준선을 아직 검증하지 않았어요. 운율 점수는 맞지 않는 기준에 대보이는 대신 숨겨요.",
        "measured": "측정됨", "hidden": "기준선 없음",
        "qualityScorecard": "품질 스코어카드", "block": "블록",
        "gatePass": "품질 게이트 통과",
        "qualityReport": "품질 리포트", "jobDetailT": "작업 상세", "inspectorT": "인스펙터",
        "hintStudio": "원고를 생성하면 여기에 블록별 품질 스코어카드가 보여요.",
        "hintVoices": "목소리를 선택하거나 프로필을 열면 버전과 원본 클립을 볼 수 있어요.",
        "hintDenoise": "파일을 가져와 정리를 실행하면 여기에 품질 리포트가 보여요.",
        "hintGeneric": "맥락에 맞는 상세 정보가 여기에 보여요.",

        "setGeneral": "일반", "setModels": "모델", "setAudio": "오디오",
        "setPrivacy": "개인정보", "setMcp": "MCP 서버", "setAbout": "정보",
        "setLanguage": "언어", "setLangTitle": "언어",
        "setLangBlurb": "인터페이스 언어를 설정해요. 각 목소리는 만들 때 고른 자기 언어를 그대로 유지해요.",
        "interfaceLanguage": "인터페이스 언어",
        "interfaceLangDetail": "Vocast의 버튼·라벨·문구가 쓰는 언어예요",
        "applyNow": "즉시 적용, 재시작 없음",
        "voiceLangSetting": "목소리 언어",
        "voiceLangSettingDetail": "여기가 아니라, 목소리를 만들 때 각각 정해요",
        "guaranteeNote": "인터페이스 언어를 바꿔도 목소리는 바뀌지 않아요. 각 목소리는 녹음된 언어를 그대로 유지해요.",
        "obLangTitle": "언어를 선택하세요",
        "obLangBody": "Vocast 인터페이스의 언어를 정하는 설정이에요. 각 목소리의 언어는 나중에 만들 때 따로 골라요.",
        "obLangHint": "macOS에서 감지했어요. 설정에서 언제든 바꿀 수 있어요.",
        "continue": "계속",

        // MARK: added from i18n-strings.md handoff
        "obWelcomeTitle": "당신의 목소리, 당신의 맥에서",
        "obWelcomeBody": "목소리를 복제하고, 어떤 원고든 낭독하고, 오디오를 정리해요. 계정도 서버도 없어요. 전부 이 맥에서 실행되고, 최초 모델 다운로드 이후에는 오프라인에서 동작해요.",
        "obPillLocal": "이 맥에서 실행",
        "obPillNoUpload": "업로드 없음",
        "obPillOffline": "오프라인 동작",
        "obGetStarted": "시작하기",
        "obTierBalanced": "균형",
        "obTierBalancedBody": "빠른 음성 모델과 전사를 함께 받아요.",
        "obTierHighQ": "고품질",
        "obTierHighQBody": "더 크고 품질 높은 음성을 추가해요.",
        "obDownloadModels": "모델 다운로드",
        "obDownloadNote": "이 맥에 한 번만 받아 앱 전용 폴더에 보관해요. 업로드되는 건 없어요.",
        "obPreparingEngine": "이 맥에서 엔진을 준비하고 있어요.",
        "obDownloading": "다운로드 중",
        "obModelsReady": "모든 모델 다운로드 완료",
        "obMicTitle": "마이크 접근",
        "obMicBody": "Vocast가 음성 샘플을 녹음하려면 마이크가 필요해요. 녹음은 이 기기에만 남고 업로드되지 않아요.",
        "obMicAllow": "마이크 허용",
        "obMicNotNow": "나중에",
        "obReadyTitle": "준비가 끝났어요",
        "obReadyBody": "목소리 프로필을 만들어 낭독을 시작하거나, 먼저 스튜디오를 둘러보세요.",
        "obReadyCreate": "첫 목소리 만들기",
        "obReadyExplore": "스튜디오 둘러보기",
        "dnDropTitle": "오디오나 영상 파일을 끌어다 놓으면 정리해요",
        "dnFormats": "WAV, MP3, M4A, MP4, MOV. 이 맥에서 처리돼요.",
        "dnChooseFile": "파일 선택",
        "dnRecentJobs": "최근 작업",
        "dnModeStandard": "표준",
        "dnModeStandardBody": "빠른 필터링이에요. 규칙적인 배경 소음과 웅웅거림을 가볍게 걷어내요.",
        "dnModeResynth": "리신스",
        "dnModeResynthBody": "전체 재합성이에요. 시간이 더 걸리지만 목소리를 다시 만들어 가장 깨끗한 결과를 내요.",
        "dnNotInstalled": "미설치",
        "dnStartCleanup": "정리 시작",
        "dnCleaning": "오디오 정리 중",
        "dnExport": "정리된 파일 내보내기",
        "dnOriginal": "원본",
        "dnCleaned": "정리본",
        "dnCleanedStatus": "정리됨 · {mode}",
        "dnNow": "지금: {side}",
        "dnSpeechPreservedTail": "음성 보존",
        "taskGroupRunning": "진행 중",
        "taskGroupQueued": "대기열",
        "taskGroupDone": "완료",
        "taskWaiting": "대기 중",
        "taskFailed": "실패",
        "taskOpen": "열기",
        "taskCancel": "취소",
        "taskDismiss": "닫기",
        "vBuildingTitle": "목소리 프로필을 만드는 중",
        "vResultTitle": "목소리 프로필 준비 완료",
        "vResultBody": "생성 결과는 앱이 당신의 목소리에서 측정한 리듬과 톤을 따라가요. 나중에 클립을 더 추가해 이 프로필을 보강할 수 있어요.",
        "vStartNarrating": "낭독 시작",
        "vViewInLibrary": "라이브러리에서 보기",
        "vDefaultPill": "기본",
        "vVersionHistory": "버전 기록",
        "vOneVersion": "이 프로필에는 버전이 하나예요.",
        "vCurrent": "현재",
        "vRollBack": "되돌리기",
        "vSourceClips": "원본 클립",
        "vReinforce": "보강",
        "vSetDefault": "기본으로 설정",
        "vDeleteProfile": "프로필 삭제",
        "vNotFound": "프로필을 찾을 수 없어요.",
        "vLevelLabel": "LVL",
        "setGeneralBlurb": "모양새, 시작, 기본 동작이에요.",
        "setAppearance": "모양새",
        "setAppearanceSub": "지금은 다크 테마만 있어요.",
        "setLaunchLogin": "로그인 시 실행",
        "setDefaultProfile": "기본 목소리 프로필",
        "setModelsBlurb": "다운로드한 음성·전사 모델을 앱 전용 폴더에 보관해요. 업로드되는 건 없어요.",
        "setDownloadHighQ": "고품질 음성 모델 다운로드 (2.9 GB)",
        "setAudioBlurb": "입력 장치와 내보내기 형식이에요.",
        "setInputDevice": "입력 장치",
        "setExportFormat": "내보내기 형식",
        "setSampleRate": "샘플레이트",
        "setPrivacyBlurb": "모든 생성과 정리가 기기에서 일어나요. 계정도 서버도 텔레메트리도 없어요.",
        "setPrivacyStatus": "개인정보와 로컬 상태",
        "setMcpBlurb": "AI 에이전트(예: Claude)가 로컬 MCP 서버를 통해 이 맥의 Vocast 기능을 호출하게 해요. 기본은 꺼짐이에요. 네트워크로 노출되는 건 없어요.",
        "setMcpEnable": "로컬 MCP 서버 켜기",
        "setMcpExposed": "노출되는 동작",
        "setMcpEmpty": "엔진이 아직 사용 가능한 도구를 알려주지 않았어요.",
        "setAbtVersion": "버전",
        "setAbtLicense": "라이선스",
        "setAbtRequirements": "요구 사양",
        "setAbtLicenseValue": "일회성 구매, $49",
        "setAbtRequirementsValue": "macOS 14 이상, Apple Silicon",
        "scSubMetrics": "세부 지표",
        "scPNSName": "운율 노스스타",
        "scSpeechPreserved": "음성 보존",
        "scPauseSupp": "묵음 억제",
        "scVoiceSim": "목소리 유사도",
        "scSubEnding": "끝맺음 스타일",
        "scSubStress": "에너지 강세",
        "scSubDrop": "끝음 내림",
        "scSubClarity": "발음 명료도",
        "inspEtaNote": "예상 시간은 이런 작업이 이 맥에서 실제로 걸린 시간을 바탕으로 해요.",
        "scFootnotePNS": "PNS는 운율 노스스타예요. 리듬·강조·구절 나눔을 당신의 목소리에 견줘 채점해요. 세부 점수는 0에서 1까지고 높을수록 좋아요. 82 이상이면 품질 기준을 충족해요. 이 맥에서 측정했어요.",
        "scFootnoteDenoise": "음성 보존은 목소리 에너지가 얼마나 남았는지를, 묵음 억제는 조용한 구간에서 소음을 얼마나 걷어냈는지를 뜻해요. 이 맥에서 측정했어요.",
        "btnCancel": "취소",

        // MARK: Part 2 census + Part B + D1 (second-tier strings, wired 2026-07-23)
        "menuNewNarration": "새 낭독",
        "menuNewVoice": "새 목소리",
        "menuSettings": "설정",
        "menuImportToClean": "정리할 오디오 가져오기",
        "menuRender": "생성",
        "menuRenderNarration": "낭독 생성",
        "menuRegenerateBlock": "블록 재생성",
        "menuToggleInspector": "인스펙터 토글",
        "menuSearch": "검색",
        "menuGroupVoice": "목소리",
        "menuPause": "일시정지",
        "menuPlay": "재생",
        "stageRendering": "생성 중",
        "stageCleaning": "정리 중",
        "stageBuilding": "빌드 중",
        "stageRerendering": "다시 생성 중",
        "stageRendered": "생성 완료",
        "stPreparing": "준비 중",
        "stPreparingVoice": "목소리 준비 중",
        "stGeneratingSpeech": "음성 생성 중",
        "stComposing": "구성 중",
        "stGenerating": "생성 중",
        "stAnalyzingVoice": "목소리 분석 중",
        "stMeasuringStyle": "말투 측정 중",
        "stPreparingClips": "클립 준비 중",
        "stAnalyzingClips": "클립 분석 중",
        "stReadingFile": "파일 읽는 중",
        "stBuildingPreview": "미리듣기 만드는 중",
        "stMeasuringQuality": "품질 측정 중",
        "stCleaningAudio": "오디오 정리 중",
        "toNarrationReady": "낭독이 준비됐어요.",
        "toBlockRerendered": "블록 {n}을 다시 생성했어요.",
        "toVoiceReady": "목소리 프로필이 준비됐어요.",
        "toProfileReinforced": "프로필을 보강했어요.",
        "toCleanupDone": "정리를 마쳤어요, {mode} 모드.",
        "toCleanedExported": "정리된 파일을 내보냈어요.",
        "toProfileDeleted": "프로필을 삭제했어요.",
        "toSetDefault": "기본으로 설정했어요.",
        "toNarrationExported": "낭독을 다운로드 폴더로 내보냈어요.",
        "toBlocksExported": "선택한 블록을 다운로드 폴더로 내보냈어요.",
        "toCleanedExportedDl": "정리된 파일을 다운로드 폴더로 내보냈어요.",
        "toRolledBack": "v{n}으로 되돌렸어요.",
        "errEngineUnreachable": "로컬 엔진에 연결할 수 없어요. 실행 중인가요?",
        "errEngineUnreachableShort": "로컬 엔진에 연결할 수 없어요.",
        "errDownloadStart": "모델 다운로드를 시작할 수 없어요. 엔진이 실행 중인가요?",
        "errNoSingleBlock": "이 낭독은 개별 블록을 재생성할 수 없어요. 먼저 다시 생성해 주세요.",
        "errMicStart": "마이크를 시작할 수 없어요. 마이크 접근을 허용하고 다시 시도해 주세요.",
        "errNeedOneLine": "먼저 문장을 하나 이상 녹음해 주세요.",
        "errRollback": "되돌릴 수 없어요.",
        "errReinforce": "보강에 실패했어요.",
        "errReinforceProfile": "프로필을 보강할 수 없어요.",
        "errImportFirst": "먼저 파일을 가져와 주세요.",
        "errExportCleaned": "정리된 파일을 내보낼 수 없어요.",
        "errDownloadError": "다운로드 오류: {detail}",
        "errNarrationFailed": "낭독 실패: {detail}",
        "errBlockRerenderFailed": "블록 {n}을 다시 생성할 수 없어요: {detail}",
        "errBuildFailed": "빌드 실패: {detail}",
        "errCleanupFailed": "정리 실패: {detail}",
        "jobType": "유형",
        "jobTarget": "대상",
        "jobProfile": "프로필",
        "jobElapsed": "경과",
        "inspNoScores": "이 블록에 대한 품질 점수를 엔진이 보고하지 않았어요.",
        "inspSelectJob": "진행 중인 작업을 선택하면 진행 상황과 상세를 볼 수 있어요.",
        "jobKindNarration": "낭독 생성",
        "jobKindDenoise": "잡음 제거",
        "jobKindVoiceBuild": "목소리 프로필 빌드",
        "inspMetaBlock": "블록 {n}",
        "inspMetaCleaned": "정리됨",
        "inspMetaRunning": "진행 중",
        "scNeedsAttention": "확인 필요: {reason}",
        "scReasonBelowBar": "운율이 82 품질 기준 아래예요",
        "scReasonSubWeak": "{metric}이 목표 아래예요",
        "scReasonSimLow": "목소리 유사도가 목표 아래예요",
        "scReasonSpeechLoss": "음성 손실이 목표를 넘었어요",
        "dnSubSim": "정리된 목소리가 원본과 얼마나 가까운지예요.",
        "dnSubSpeech": "목소리 에너지가 얼마나 남았는지예요.",
        "dnSubPause": "조용한 구간에서 걷어낸 소음이에요.",
        "dnProcessingSubhead": "{mode} 모드, 이 맥에서.",
        "obDownloadHeading": "음성 모델 다운로드",
        "obDownloadHeadingDone": "음성 모델 준비 완료",
        "mdlVoiceFast": "음성 모델 (빠름)",
        "mdlVoiceHighQ": "음성 모델 (고품질)",
        "mdlTranscription": "전사 모델",
        "mdlVoiceGeneric": "음성 모델",
        "obGbOnMac": "이 맥에서 {n} GB",
        "mdlNoiseRemoval": "잡음 제거",
        "setInstalled": "설치됨",
        "setDownloadingGB": "다운로드 중, {a} / {b} GB",
        "setBundled": "기본 포함",
        "privSubLocal": "생성은 이 기기만 사용해요.",
        "privSubNoUpload": "오디오는 기기 밖으로 나가지 않아요.",
        "privSubOffline": "최초 실행 시 모델 다운로드 이후예요.",
        "privWhereStored": "데이터 저장 위치",
        "mcpRunning": "실행 중 · localhost만",
        "mcpDisabled": "꺼짐",
        "mcpActionEnabled": "켜짐",
        "mcpActionDisabled": "꺼짐",
        "vRecStatusRecording": "녹음 중",
        "vRecStatusCaptured": "녹음됨",
        "vRecStatusReady": "녹음 준비 완료",
        "vGuideWaiting": "엔진의 안내 문장을 기다리는 중이에요.",
        "vBuildSubline": "이 맥에서 {stage}. 백그라운드 작업으로 실행되니 계속 작업할 수 있어요.",
        "vResultSubline": "{name}이 이제 라이브러리에 있고 기본으로 설정됐어요.",
        "vStatClips": "개 클립 분석됨",
        "vStatDuration": "목소리 분량",
        "vStatVersion": "버전",
        "vDefaultName": "내 목소리",
        "vBuildNow": "지금 빌드 ({n})",
        "vCurrentVersion": "현재 버전",
        "vEarlierVersion": "이전 버전",
        "vCardClips": "{version} · 클립 {n}개",
        "vMetaSourceClips": "{version} · 원본 클립 {n}개 · {duration}",
        "vSourceBlurb": "클립 {n}개, 총 {duration}. 오디오 파일을 여기로 끌어다 놓으면 목소리를 더해 이 프로필을 보강해요.",
        "stuScorecardNote": "당신의 생성 결과를 이 맥에서 측정했어요.",
        "etaFinishing": "마무리 중",
        "vpA11yProfile": "목소리 프로필",
        "vpA11yProfileHint": "목소리 프로필 목록을 열어요",
        "vpA11yProfiles": "목소리 프로필",
        "vpEmptyNoProfiles": "아직 목소리 프로필이 없어요",
        "jobTitleNarration": "낭독 생성",
        "jobTitleNarrationBlock": "낭독 생성, 블록 {n}",
        "jobTitleVoiceBuild": "목소리 프로필 빌드",
        "jobTitleDenoise": "잡음 제거, {file}",
        "jobSubTts": "{profile} · 이 맥에서 TTS",
        "jobSubClipsAnalyzing": "클립 {n}개 · 분석 중",
        "jobSubClips": "클립 {n}개",
        "jobSubMode": "{mode} 모드",
        "jobTargetBlockOf": "{total} 중 블록 {n}",
        "jobTargetClips": "클립 {n}개",
        "jobTimeJustNow": "방금",
        "jobTimeFailed": "실패",
        "jobElapsedS": "{n}초 경과",
        "jobSpeechPreservedPct": "음성 보존 {n}%",

        // Authored in-house to close small gaps the designer handoff did not cover.
        // Low-visibility strings; flag for ratification in a later handoff pass.
        "stDone": "완료",
        "jobTargetNarration": "낭독",
        "vNoProfileFacts": "목소리 프로필 없음",
        "dnProcessingSubheadStage": "{stage}, 이 맥에서.",
        "errUnknownDetail": "알 수 없는 오류",

        // Studio 나레이션 라이브러리.
        "libSearchPlaceholder": "나레이션 검색",
        "libSortNewest": "최신순",
        "libBlocksN": "{n} 블록",
        "libVoiceNone": "목소리 없음",
        "rowOpen": "열기", "rowRename": "이름 변경", "rowDuplicate": "복제",
        "rowExport": "내보내기", "rowDelete": "삭제",
        "libEmptyTitle": "아직 나레이션이 없어요",
        "libEmptyBody": "원고를 붙여넣고 목소리로 생성하면 여기에 저장돼요.",
        "libEmptyCta": "새 나레이션",
        "editorVoiceGone": "이 나레이션의 목소리가 삭제됐어요. 재생과 내보내기는 되지만, 다시 생성하려면 목소리를 다시 골라 주세요.",
        "backToLibrary": "라이브러리",
        "untitledNarration": "제목 없는 나레이션",
        "exportTitle": "내보내기",
        "expAudioH": "오디오", "expSubH": "자막", "expProjectH": "프로젝트",
        "expScopeWhole": "전체 나레이션", "expScopeSelected": "선택한 블록",
        "expAudioHint": "전체 나레이션이나 선택한 블록을 오디오 파일로 내보내요.",
        "expSubHint": "전체 나레이션을 블록에 맞춰 타이밍한 자막이에요.",
        "expProjHint": "백업하거나 다른 맥으로 옮겨요.",
        "expProjectExport": ".vocast 파일 내보내기", "expProjectImport": ".vocast 파일 가져오기",
        "exportedTitle": "내보내기 완료",
        "exportedBody": "{file}, 다운로드 폴더에 저장했어요.",
        "renameTitle": "이름 변경",
        "renameHint": "제목은 원고 첫 줄에서 자동으로 만들어져요.",
        "renameSave": "저장",
        "delTitle": "이 나레이션을 삭제할까요",
        "delBody": "삭제하면 원고와 생성된 오디오가 함께 지워져요. 되돌릴 수 없어요.",
        "delConfirm": "삭제", "delCancel": "취소",
        "libSoon": "곧 지원돼요.",
        "toNarrationDeleted": "나레이션을 삭제했어요.",
        "errOpenNarration": "나레이션을 열 수 없어요.",
        "errExport": "내보내기에 실패했어요.",
        "relJustNow": "방금",
        "relMinAgo": "{n}분 전", "relHourAgo": "{n}시간 전",
        "relYesterday": "어제", "relDayAgo": "{n}일 전", "relLastWeek": "지난주",
    ]
}
